### ISSUE TITLE
ソフトバンクペイメント決済：接続に失敗

### ISSUE THREAD

**Issue by chungth** [fumikito/Literally-WordPress#138]
お世話になっております。
Literally-WordPress プラグインを採用して、 ソフトバンクペイメントを設定しましたが、チェックアウトする際、下記写真のような状態になりました。
何か原因を教えて頂けませんか。
宜しくお願い申し上げます。
<img width="964" alt="screen shot 2015-12-02 at 12 31 48 am" src="https://cloud.githubusercontent.com/assets/2556644/11505212/ab86b5de-988c-11e5-806b-38c7be17617c.png">

**Comment by chungth** [comment]
自分でデーバグできました。

**Comment by fumikito** [comment]
@chungth あ、すみません、直ったようでなによりです。

**Comment by chungth** [comment]
@fumikito ありがとうございます。

ちなみに、ソフトバンクペイメントのスマホ課金は現在サポートしていますか。

**Comment by fumikito** [comment]
@chungth スマホ課金というのは、大手キャリアの決済代行サービスのことですか？
http://www.sbpayment.jp/asp/method/mobile/
こちらはサポートされていません。

実はいまのところ、このプラグインではなく別の決済プラグインをリリースしようという計画を立てています。したがって、新機能は追加されません。

**Comment by chungth** [comment]
@fumikito というのはこのプラグインの開発は続きませんでしょうか。
新決済プラグインの名前を教えて頂けませんか。

**Comment by fumikito** [comment]
@chungth はい、続きません。
新決済プラグインは現在開発中です。そちらにLiterally WordPressとの互換性をもたせるかどうかは現在検討中です。

**Comment by chungth** [comment]
@fumikito 現在  Literally-Wordpressを設定して、スマホ課金を追加しようと考えていますが、Fumikitoさんはこのプラグインの開発を中止する予定ので、残念ですね。

**Comment by chungth** [comment]
@fumikito ところで、このプラグインのライセンスを教えていただけないでしょうか。

**Comment by fumikito** [comment]
@chungth  GPL 2.0 and later です。
